In [1]:
import json
import pandas as pd

In [2]:
table = {'sha256': list(), 'label': list(), 'entropy': list(), 'name': list(), 'size': list()}

for n in range(6):
    num = 0
    with open(f'/content/drive/MyDrive/최종프로젝트_7조/dataset/train_features_{n}.jsonl') as file:
        while True:
            line = file.readline()
            if not line:
                break
            line_json = json.loads(line)
            table['sha256'].append(line_json['sha256'])    
            table['label'].append(line_json['label'])
            entropy, name, size = list(), list(), list()
            for sec in line_json['section']['sections']:
                entropy.append(round(sec['entropy'], 4))
                name.append(sec['name'])
                size.append(sec['size'])
            table['entropy'].append(entropy)
            table['name'].append(name)
            table['size'].append(entropy)
            num += 1
            if num % 1000 == 0:
                print(f'\rjsonl{n} : {num}', end='')        
        print(f'\rjsonl{n} : {num}')
    
train_df = pd.DataFrame(table)
train_df['cond1'] = train_df['size'].map(lambda x: 1 if sum(map(lambda y: 0 if y else 1, x)) else 0)
train_df['cond2'] = train_df['entropy'].map(lambda x: 1 if sum(map(lambda y: 0 if 0 < y < 7 else 1, x)) else 0)
train_df['cond_1or2'] = train_df['cond1'] | train_df['cond2']

train_df.to_csv(f'/content/drive/MyDrive/최종프로젝트_7조/dataset/train_main_features_NJ.csv')

train_df

jsonl0 : 50000
jsonl1 : 170000
jsonl2 : 170000
jsonl3 : 170000
jsonl4 : 170000
jsonl5 : 170000

                                                   sha256  ...  cond_1or2
0       0abb4fda7d5b13801d63bee53e5e256be43e141faa077a...  ...          1
1       d4206650743b3d519106dea10a38a55c30467c3d9f7875...  ...          1
2       c9cafff8a596ba8a80bafb4ba8ae6f2ef3329d95b85f15...  ...          0
3       7f513818bcc276c531af2e641c597744da807e21cc1160...  ...          1
4       ca65e1c387a4cc9e7d8a8ce12bf1bcf9f534c9032b9d95...  ...          1
...                                                   ...  ...        ...
899995  fffe4814bd4e333d91f710df8ec2e56e31ff8afb13099b...  ...          1
899996  fffe8eafb43ce2181cb124413f2d54bf12ab99815922ab...  ...          1
899997  ffff49525f240d58e198ca4e08ea1a7fe1632bf0411950...  ...          1
899998  ffff9a65324d628e3ef0a830f5460fda18acaa02279158...  ...          1
899999  ffffe3ba2c2484d07b7104bcd8ce3da8f92e21f6d41b8d...  ...          0

[900000 rows x 8 columns]

In [3]:
table = {'sha256': list(), 'label': list(), 'entropy': list(), 'name': list(), 'size': list()}

num = 0
with open(f'/content/drive/MyDrive/최종프로젝트_7조/dataset/test_features.jsonl') as file:
    while True:
        line = file.readline()
        if not line:
            break
        line_json = json.loads(line)
        table['sha256'].append(line_json['sha256'])    
        table['label'].append(line_json['label'])
        entropy, name, size = list(), list(), list()
        for sec in line_json['section']['sections']:
            entropy.append(round(sec['entropy'], 4))
            name.append(sec['name'])
            size.append(sec['size'])
        table['entropy'].append(entropy)
        table['name'].append(name)
        table['size'].append(entropy)
        num += 1
        if num % 1000 == 0:
            print(f'\rjsonl_test : {num}', end='') 
    print(f'\rjsonl_test : {num}')

test_df = pd.DataFrame(table)
test_df['cond1'] = test_df['size'].map(lambda x: 1 if sum(map(lambda y: 0 if y else 1, x)) else 0)
test_df['cond2'] = test_df['entropy'].map(lambda x: 1 if sum(map(lambda y: 0 if 0 < y < 7 else 1, x)) else 0)
test_df['cond_1or2'] = test_df['cond1'] | test_df['cond2']

test_df.to_csv(f'/content/drive/MyDrive/최종프로젝트_7조/dataset/test_main_features_NJ.csv')

test_df

jsonl_test : 200000

                                                   sha256  ...  cond_1or2
0       0001a959869f81b94c6b380f5161cdf315203227b8bcb8...  ...          1
1       000253d72d0b303a2af97057e86301e5121be2a8705892...  ...          1
2       0002aff0af07d2fb0d4bcf978248f3de9b0709e09f7e0b...  ...          0
3       00048cd8ce4e9e981dcf2b51f7f6cac66a30c782825e06...  ...          0
4       0004949156b344dafaa673ebfdefb1460f167984099101...  ...          0
...                                                   ...  ...        ...
199995  fffe314f23cee3a68ccab272934877d3bc18ec3bd905df...  ...          0
199996  fffe7a1b23e04facc9ca91a93ac4a34e8b3040e023dbde...  ...          0
199997  fffe801f51e7ec931515aa49a3d157a9c0fbcdca8c9d80...  ...          0
199998  fffe92f9593649c4a7050302368189de45e2c1c06b04ea...  ...          0
199999  ffffb259a4c5e25ae1437af59caafb718cf8879187cc8c...  ...          0

[200000 rows x 8 columns]